id: P004516
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6976
  title: རྒྱུན་ལྡན་ཁྲིམས་ལུགས་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    8031d67dc245497b94130019033b59dd:
      image_group_id: I3CN6978
      title: ''
      volume_number: 1
      total_pages: 131
