id: P004516
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:28:55.109432
source_metadata:
  id: bdr:W3CN6976
  title: རྒྱུན་ལྡན་ཁྲིམས་ལུགས་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    8031d67dc245497b94130019033b59dd:
      image_group_id: I3CN6978
      title: ''
      volume_number: 1
      total_pages: 131
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
